# Generated by Django 6.0.3 on 2026-03-20 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('ai_score', models.FloatField(default=0)),
                ('ai_matches', models.TextField(blank=True, null=True)),
                ('ai_decision', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review'), ('selected', 'Selected')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_type', models.CharField(max_length=50)),
                ('interviewer_name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.candidate')),
            ],
        ),
    ]
