# Generated by Django 6.0.3 on 2026-03-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_staff', 'HR Staff'), ('operations_staff', 'Operations Staff'), ('support_staff', 'Support Staff'), ('sales_staff', 'Sales Staff')], default='hr_staff', max_length=30),
        ),
    ]
