# Generated by Django 6.0.3 on 2026-03-21 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_level', models.CharField(blank=True, max_length=100, null=True)),
                ('demo_requested', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo_scheduled', 'Demo Scheduled'), ('negotiation', 'Negotiation'), ('purchase_confirmed', 'Purchase Confirmed'), ('closed_lost', 'Closed Lost')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('classification', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=20)),
                ('sent_to_operations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
